source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'thin'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

group :development, :test do
  gem 'nifty-generators'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cover_me', '>= 1.0.0.rc6'

end

