source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'thin'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

group :development do
  gem 'nifty-generators'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
end
